base:
  url: http://121.40.203.12:8888
#  url: https://desk-test.wattsonic.cn/basic-api
  username: lyy@wattsonic.com
  password: Wt1234
  username2: 11@wattsonic.com
  password2: Wt1234
#163邮箱发送企业邮箱配置
email:
  smtp_server: smtp.163.com
  port: 465
  psw: TLNOFJSYQPYWISOA
  sender: liyanyan8759@163.com
  receiver: jena.li@wattsonic.com,2972049643@qq.com
countrylist:
  name: countrylist
  request:
    method: get
    url: /countryMap/list
    data: None
  validate: None
queryByCode:
  name: queryByCode
  request:
    method: get
    url: /company/queryByCode/
    data:  289889
  validate: None
companyregister:
  name: companyregister
  request:
    method: post
    url: /company/register
    data: {"parentId":"1733050949145640962","region":"CN","address":"无锡人民路108号","contactName":"ll8759","password":"Wt123456","confirmPassword":"Wt123456","checkBox":true,"mobile":"17798736211","sex":1}
  validate: None
userregister:
  name: userregister
  request:
    method: post
    url: /user/register
    data: {
      "companyCode": "289889",
      "name": "ll8759",
      "password": "Wt123456",
      "sex": 0
    }
  validate: None

enduserregister:
  name: enduserregister
  request:
    method: post
    url: /user/end/register
    data: {
      "name": "ll8759",
      "password": "Wt123456",
      "sex": 0,
      "mobile": "1779873611"
    }
  validate: None


login:
  name: login
  request:
    method: post
    url: /login
    headers: {'Accept-Language':'en-us','Platform':'web'}
    data: {
      "password": "Wt1234",
      "username": "11@wattsonic.com"
    }
  validate: None
user_current:
  name: user_current
  request:
    method: get
    url: /user/current
    data: None
  validate: None
password:
  name: password
  request:
    method: put
    url: /user/password
    data: {
      "newPassword": "Wattsonic11",
      "oldPassword": "Wattsonic11"
    }
  validate: None


plant_number:
  name: plant_number
  request:
    method: get
    url: /v2/plant/statistics
    data: None
  validate: None
wokerorder_number:
  name: wokerorder_number
  request:
    method: get
    url: /workOrder/count?status=0
    data: None
  validate: None
ESG:
  name: ESG
  request:
    method: get
    url: /v2/plant/esg
    data: None
  validate: None

daily_grow:
  name: daily_grow
  request:
    method: get
    url: /v2/plant/dailyGrowth
    data: {
      "days":30,
      "zoneOffsetMinutes":480
    }
  validate: None
topProducts:
  name: topProducts
  request:
    method: get
    url: /v2/plant/topProducts
    data: {
      "current":1,
      "size":5,
    }
  validate: None
topDistributors:
  name: topDistributors
  request:
    method: get
    url: /v2/plant/topDistributors
    data: {
      "current":1,
      "size":10,
    }
  validate: None
topPlants:
  name: topPlants
  request:
    method: get
    url: /v2/plant/topPlants
    data: {
      "current":1,
      "size":10,
    }
  validate: None
maplist:
  name: maplist
  request:
    method: get
    url: /v2/plant/map/list
    data: {
      "keywork":'test'
    }
  validate: None
searchtips:
  name: searchtips
  request:
    method: get
    url: /v2/plant/search/tips
    data: {
      "keyword":'test'
    }
  validate: None
timezone:
  name: timezone
  request:
    method: get
    url: /dictionary/timezone
    data: None
  validate: None
creatplant1:
  name: creatplant1
  request:
    method: post
    url: /v2/plant/save
    data: {"region":"DZ","timezone":"Asia/Shanghai","address":"MXX6+46 台湾南投縣信義鄉人和村","longitude":120.960515,"latitude":23.69781,"plantPicture":"wattdesk/plant-pic.png","sex":2,"ownerName":"wer3423@#@","email":"jena98@163.com","password":"6289","installerId":"1703689154564096002","ownerType":1,"mobileSuffix":"6289","localCurrency":"USD","gridPricePerKWh":0,"subSysParams":[]}
  validate: None
creatplant2:
  name: creatplant2
  request:
    method: post
    url: /v2/plant/save
    data: {"region":"DE","timezone":"Europe/Berlin","address":"5C7X+Q6 Vogtei, 德国","longitude":10.448114230281575,"latitude":51.164466535891556,"plantPicture":"wattdesk/plant-pic.png","sex":1,"ownerName":"wer3423@#@","email":"jena98@163.com","password":"6289","installerId":"1703689154564096002","ownerType":1,"mobileSuffix":"6289","localCurrency":"CNY","gridPricePerKWh":0.5234}
  validate: None
importproduct1:
  name: importproduct1
  request:
    method: post
    url: /plant/product/import
    data: {
      "type": 1,
      "modelId": 1745254022022623233,
    }
  validate: None
importproduct2:
  name: importproduct2
  request:
    method: post
    url: /plant/product/import
    data: {
      "type": 10,
      "modelId": 1760902098704183297,
    }
  validate: None
gatewaybat1:
  name: gatewaybat1
  request:
    method: post
    url: http://172.18.30.87:8888/gateway/bat/gen2Low
    hostname: 120.26.192.77
    username: root
    password: Watts0nicqw12QW!@
    data: {
      "voltage": 289,
      "current": 99,
      "soc": 100,
      "soh": 99,
      "iotSoftwareVersion": "V1.4.6",
      "bcuInfoList": [
      {
        "voltage": 300,
        "current": 100,
        "soc": 100,
        "soh": 9,
        "softwareVersion": "V1.3.4",
        "hardwareVersion": "1.3.4",
        "totalCharge": 100,
        "totalDischarge": 99,
        "alarmMap": {
          "停机状态低-Bit3:总压低": false
        }
      }
      ]
    }
  validate: None
gatewaywat:
  name: gatewaywat
  request:
    method: post
    url: http://172.18.30.87:8888/gateway/wattmate
    hostname: 120.26.192.77
    username: root
    password: Watts0nicqw12QW!@
    data: {
      "zoneId": "Asia/Shanghai",
      "softwareVersion": "V1.2.3",
      "maxPower": 9000,
      "maxGridPower": 5000,
      "currentPower": 2000,
      "heatingCoefK": 2.88,
      "elecUsage24h": 1888,
      "injection": 1500,
      "purchase": 1000,
      "supportModeList": [
        0,
        1,
        2
      ],
      "currentMode": 0,
      "timeMode": 0,
      "maxTemp": 650,
      "allDayTargetTemp": 450,
      "initStatus": 0,
      "light1Status": 0,
      "light2Status": 0,
      "light3Status": 0,
      "light4Status": 0,
      "light5Status": 0,
      "emsComStatus": 0,
      "meterComStatus": 0,
      "pcsComStatus": 0,
      "gridAccessStatus": 0,
      "pcsAccessStatus": 0,
      "workStatus": 0,
      "heaterInfoList": [
      {
        "type": 1,
        "targetTemp": 400,
        "currentPower": 1200,
        "currentTemp": 380,
        "elecUsage24h": 180,
        "workStatus": 0
      }
      ],
      "planList": [
      {
        "endTime": 0,
        "startTime": 60,
        "targetTemp": 30
      },
      {
        "endTime": 120,
        "targetTemp": 180,
        "startTime": 40
      },
      {
        "targetTemp": 240,
        "startTime": 320,
        "endTime": 50
      },
      {
        "targetTemp": 0,
        "endTime": 0,
        "startTime": 0
      },
      {
        "endTime": 0,
        "startTime": 0,
        "targetTemp": 0
      }
      ]
    }
  validate: None
subSys:
  name: subSys
  request:
    method: get
    url: /plant/product/sn
    data: None
  validate: None
subSysbindPlant:
  name: subSysbindPlant
  request:
    method: put
    url: /plant/subSys/bindPlant
    data: {
      "subSysParams": [
      {
        "subSysName": "设备11",
        "checkCode": "888888"
      }
      ]
    }
  validate: None